# Generated by Django 5.2.11 on 2026-03-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoteSection',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('transcription_text', models.TextField(blank=True)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note_page.notesection')),
            ],
        ),
    ]
