# Generated by Django 5.2.11 on 2026-04-16 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevent',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
    ]
